version: "2"
services:

  zookeeper:
    container_name: notesApp-zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2182:2182"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: notesApp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: dresses:1:1,ratings:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  spring-app:
    container_name: notesApp
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      EMAIL_USER: "default@gmail.com"
      EMAIL_PASSWORD: "password"
